### ISSUE TITLE
Its not working

### ISSUE THREAD

**Issue by Kev1n121** [CoreyHayward/PowerToys-Run-ClipboardManager#4]
The PowerToys-Run-ClipboardManager is not working here. If I clipboard something. or couple of times with different text, I press c: in the Alt-Space powertoys Nothing happens.

**Comment by seguri** [comment]
How do I debug problems with this plugin? I followed all the instructions and nothing happens with `c:`. I'm running on v0.80.1.

**Comment by CoreyHayward** [comment]
@seguri The easiest way to debug is to follow the installation instructions and then open the project and attach the debugger to the `PowerToys.PowerLauncher.exe` process. You should then be able to debug the code

**Comment by seguri** [comment]
@CoreyHayward I'm a mac user, so I'm not particularly inclined in starting debugging windows processes for a malfunctioning plugin, but I can give this a try if it's quick. Where do I find PowerToys.PowerLauncher.exe? I see only PowerToys.Settings.exe running in the task manager.
Are there no easy log file to analyze for this problem?

**Comment by CoreyHayward** [comment]
@seguri Apologies, by "debug" I assumed you meant actually debugging the running code, I should have specified to use Visual Studio for this. However, logs should be available at the following path `\%LocalAppData%\Microsoft\PowerToys\PowerToys Run\Logs\` which should detail any errors or exceptions which may be occurring.

**Comment by seguri** [comment]
Does this:

```
[2024-04-24 10:38:01.0399] [ERROR] [C:\a\_work\1\s\src\modules\launcher\PowerLauncher\Plugin\PluginManager.cs::239]
-------------------------- Begin exception --------------------------
Message: Exception for plugin <Windows Uri Handler> when query <c:>

Exception full name  : System.UriFormatException
Exception message    : Invalid URI: The format of the URI could not be determined.
Exception stack trace:
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at Microsoft.Plugin.Uri.UriHelper.ExtendedUriParser.TryParse(String input, Uri& webUri, Uri& systemUri)
   at Microsoft.Plugin.Uri.Main.Query(Query query)
   at PowerLauncher.Plugin.PluginManager.<>c__DisplayClass23_0.<QueryForPlugin>b__0()
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action)
   at PowerLauncher.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query, Boolean delayedExecution)
Exception source     : System.Private.Uri
Exception target site: Void CreateThis(System.String, Boolean, System.UriKind, System.UriCreationOptions ByRef)
Exception HResult    : -2146233033
-------------------------- End exception --------------------------
```

or this:

```
[2024-04-24 08:03:28.7587] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\UWPApplication.cs::623]
-------------------------- Begin exception --------------------------
Message: 	Error status: KNOWN
		Program path: C:\Program Files\WindowsApps\Clipchamp.Clipchamp_3.0.10220.0_neutral__yxz26nhyzhsrt
		Exception thrown in called method: Not available
		Possible interpretation of the error: |Clipchamp.Clipchamp_yxz26nhyzhsrt!App can't find logo uri for Images\AppList.png in package location: C:\Program Files\WindowsApps\Clipchamp.Clipchamp_3.0.10220.0_neutral__yxz26nhyzhsrt
		Possible resolution: Can be ignored and PowerToys Run should still continue, however the program may not be loaded

Exception full name  : System.IO.FileNotFoundException
Exception message    : Unable to find the specified file.
Exception stack trace:

Exception source     : 
Exception target site: 
Exception HResult    : -2147024894
-------------------------- End exception --------------------------
```

tell you something?

**Comment by CoreyHayward** [comment]
@seguri unfortunately not those are errors from other plugins, feel free to send the whole log file and i can take a look when I get a chance
